// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://droarcvgwinaqibftmsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyb2FyY3Znd2luYXFpYmZ0bXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjU3NzMsImV4cCI6MjA1NzkwMTc3M30.o0DnWgXR_BYbbch5IDYlqxEoFcMwDHrWCgyw4dSbnu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);